name: Sync Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
        node-version: [ "20.5.1" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run sync
        env:
          SCHEDULE_URL: ${{ secrets.SCHEDULE_URL }}"
        run: |
          python sync_schedule.py

      - name: Install UI deps
        run: |
          npm install

      - name: Build UI
        run: |
          npm run build

      - name: Configure git
        run: |        
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy UI
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export DATE=$(date +'%Y-%m-%d')

          git add .

          !(git diff-index --quiet HEAD --) && \
            git commit -am "Update schedule $DATE" && \
            git push
